README.md
Signed-off-by: Vigith Maurice <vigith@gmail.com>
Update readme
=> doc: update UDSink

pynumaflow/_constants.py
=> update function socket

examples/function/flatmap/Dockerfile, examples/function/flatmap/Makefile, examples/function/flatmap/README.md, examples/function/flatmap/entry.sh, examples/function/flatmap/example.py, examples/function/flatmap/pyproject.toml, examples/function/forward_message/pyproject.toml, examples/sink/simplesink/Dockerfile, examples/sink/simplesink/Makefile, examples/sink/simplesink/README.md, examples/sink/simplesink/example.py, examples/sink/simplesink/pipeline-numaflow.yaml, examples/sink/simplesink/pyproject.toml
=> chore: flatmap and simple udsink examples push to quay

.github/workflows/pypi.yaml, poetry.lock, pynumaflow/_constants.py, pynumaflow/tests/function/test_server.py, pyproject.toml
- Remove unused dependencies
- Add auto pypi publish workflow (Closing #7 )
=> chore: remove unwanted dependencies

.github/workflows/changelog.yml, .hack/changelog.sh
=> chore: add auto changelog generation

pynumaflow/function/server.py, pynumaflow/sink/server.py, pynumaflow/tests/function/test_server.py, pynumaflow/tests/sink/test_server.py, pyproject.toml
=> fix: catch exception in udf and udsink

pyproject.toml
Bumping version to v0.2.5 for new release.
=> chore: bump version to v0.2.5

pynumaflow/function/server.py
=> chore: debug logs

.codecov.yml, .coveragerc, pynumaflow/function/_dtypes.py, pynumaflow/function/server.py, pynumaflow/sink/_dtypes.py, pynumaflow/sink/server.py, pynumaflow/tests/function/test_messages.py
- udf multi-threaded sync server
- udsink multi-threaded sync server
- udf and udsink sync servers with migration threadpool
Note: Since most of the changes are in the server function, the codecov is failing.
Closes #25
=> feat: introduces sync gRPC server 

README.md, pyproject.toml
=> chore: bump version to v0.2.6

README.md
Signed-off-by: David Seapy <dseapy@gmail.com>
Updates udf and udsink links in README.md
=> docs: update udf and udsink links in README.md

.flake8, .github/workflows/ci.yml, .github/workflows/coverage.yml, .github/workflows/lint.yml, .github/workflows/pypi.yaml, .gitignore, poetry.lock, pyproject.toml
- fix flake8 config error
- move dev dependencies as optional and update github workflows
- improve gitignore
=> fix: .flake8 file

pyproject.toml
=> chore: bump version to v0.3

pyproject.toml
=> chore: bump version to v0.3.1

pynumaflow/function/__init__.py, pynumaflow/function/_dtypes.py, pynumaflow/tests/function/test_messages.py, pytest.ini
Adding slots to important data types to improve performance by 20%.
=> perf: improve performance by adding slots

poetry.lock, pyproject.toml
Signed-off-by: San Nguyen <vinhsannguyen91@gmail.com>
=> chore: update protobuf version

pynumaflow/__init__.py
Signed-off-by: San Nguyen <vinhsannguyen91@gmail.com>
=> fix: stream to stdout stderr based on log level

README.md, examples/developer_guide/example.py, examples/function/counter/example.py, examples/function/flatmap/example.py, examples/function/forward_message/example.py, pynumaflow/_constants.py, pynumaflow/function/_dtypes.py, pynumaflow/function/_udfunction_pb2.pyi, pynumaflow/function/proto/udfunction.proto, pynumaflow/function/proto/udfunction_pb2.py, pynumaflow/function/proto/udfunction_pb2_grpc.py, pynumaflow/function/server.py, pynumaflow/sink/_dtypes.py, pynumaflow/sink/proto/udsink.proto, pynumaflow/sink/proto/udsink_pb2.py, pynumaflow/sink/proto/udsink_pb2_grpc.py, pynumaflow/sink/server.py, pynumaflow/tests/function/test_async_server.py, pynumaflow/tests/function/test_async_server_err.py, pynumaflow/tests/function/test_datatypes.py, pynumaflow/tests/function/test_messages.py, pynumaflow/tests/function/test_messagets.py, pynumaflow/tests/function/test_server.py, pynumaflow/tests/sink/test_datatypes.py
=> feat: support for multi keys

examples/function/event_time_filter/example.py, pynumaflow/function/server.py
fixing minor gaps from my previous pr
=> chore: convert keys to list

README.md
=> fix: doc typo fix

README.md
Add document to explain how to use datum metadata in UDF.
=> doc: explain how to use datum metadata.

README.md, examples/function/even_odd/example.py, examples/function/event_time_filter/example.py, examples/function/flatmap/example.py, examples/function/forward_message/example.py, pynumaflow/function/__init__.py, pynumaflow/function/server.py, pynumaflow/sink/__init__.py, pynumaflow/sink/async_sink.py, pynumaflow/sink/server.py, pynumaflow/tests/function/test_sync_server.py, pynumaflow/tests/sink/test_server.py
=> chore: rename sync_server to server

examples/function/event_time_filter/example.py
update event time filter transformer to use tag for conditional forwarding.
=> fix: update event time filter transformer to use tag

pynumaflow/sink/_dtypes.py, pynumaflow/sink/async_sink.py, pynumaflow/sink/server.py, tests/sink/test_responses.py
- add slots
- use dataclasses
- add docstrings
- fix typing
=> chore: improve udsink dtypes

examples/function/flatmap_stream/Dockerfile, examples/function/flatmap_stream/Makefile, examples/function/flatmap_stream/README.md, examples/function/flatmap_stream/entry.sh, examples/function/flatmap_stream/example.py, examples/function/flatmap_stream/pyproject.toml, pynumaflow/function/async_server.py
Add a map stream udf example for flatmap.
=> chore: add map stream udf example

pyproject.toml
=> chore: bump version to '0.4.2'

examples/function/flatmap_stream/pyproject.toml, pyproject.toml
=> Update flatmap stream sdk version dependency

pynumaflow/_constants.py
=> chore: set default max gRPC msg size to 64 MB

pyproject.toml
=> chore: update version

examples/sideinput/simple-sideinput/pipeline-numaflow.yaml, examples/sideinput/simple-sideinput/udf/Dockerfile, examples/sideinput/simple-sideinput/udf/Makefile, examples/sideinput/simple-sideinput/udf/entry.sh, examples/sideinput/simple-sideinput/udf/example.py, examples/sideinput/simple-sideinput/udf/pyproject.toml
=> chore: add python side input watcher example

examples/source/async-source/Dockerfile, examples/source/async-source/Makefile, examples/source/async-source/README.md, examples/source/async-source/entry.sh, examples/source/async-source/example.py, examples/source/async-source/pipeline-numaflow.yaml, examples/source/async-source/pyproject.toml, pynumaflow/sourcer/async_server.py, pyproject.toml
=> fix: async source init 

examples/sourcetransform/event_time_filter/example.py, pynumaflow/_constants.py, pynumaflow/sourcetransformer/__init__.py, pynumaflow/sourcetransformer/_dtypes.py, tests/sourcetransform/test_messages.py
require event time when dropping messages.
=> fix: require event time when dropping messages

examples/map/even_odd/pyproject.toml, examples/map/flatmap/pyproject.toml, examples/map/forward_message/pyproject.toml, examples/map/multiproc_map/pyproject.toml, examples/mapstream/flatmap_stream/pyproject.toml, examples/reduce/asyncio-reduce/pyproject.toml, examples/reduce/counter/pyproject.toml, examples/sideinput/simple-sideinput/pyproject.toml, examples/sideinput/simple-sideinput/udf/pyproject.toml, examples/sink/async_log/pyproject.toml, examples/sink/log/pyproject.toml, examples/source/async-source/pyproject.toml, examples/source/simple-source/pyproject.toml, examples/sourcetransform/event_time_filter/pyproject.toml, pyproject.toml
=> chore: update SDK version to 0.6.0

pynumaflow/_constants.py, pynumaflow/info/types.py, pynumaflow/mapper/async_server.py, pynumaflow/mapper/multiproc_server.py, pynumaflow/mapper/sync_server.py, pynumaflow/mapstreamer/async_server.py, pynumaflow/reducer/async_server.py, pynumaflow/shared/server.py, pynumaflow/sideinput/server.py, pynumaflow/sinker/async_server.py, pynumaflow/sinker/server.py, pynumaflow/sourcer/async_server.py, pynumaflow/sourcer/server.py, pynumaflow/sourcetransformer/multiproc_server.py, pynumaflow/sourcetransformer/server.py
Implement  [#1456](https://github.com/numaproj/numaflow/issues/1456) for python sdk
=> chore: add separate server info file paths for all services

examples/developer_guide/README.md
=> chore: refactor developer guide

.github/workflows/coverage.yml, pynumaflow/info/types.py, pynumaflow/shared/server.py, tests/test_info_server.py
related to: [#1504](https://github.com/numaproj/numaflow/issues/1504)
=> chore: add minimum client version to server info class

development.md, releases.md
=> chore: add release documentation

examples/sink/async_log/example.py, examples/sink/log/Makefile, examples/sink/log/example.py, pynumaflow/_constants.py, pynumaflow/proto/sinker/sink.proto, pynumaflow/proto/sinker/sink_pb2.py, pynumaflow/sinker/_dtypes.py, pynumaflow/sinker/async_server.py, pynumaflow/sinker/server.py, pynumaflow/sinker/servicer/async_servicer.py, pynumaflow/sinker/servicer/sync_servicer.py, pynumaflow/sinker/servicer/utils.py, tests/map/test_multiproc_mapper.py, tests/sink/test_async_sink.py, tests/sink/test_responses.py, tests/sink/test_server.py, tests/sourcetransform/test_multiproc.py
=> feat: add fallback sink support

pynumaflow/_constants.py, pynumaflow/reducestreamer/servicer/task_manager.py, pynumaflow/shared/server.py, pynumaflow/sideinput/servicer/servicer.py, pynumaflow/sinker/servicer/async_servicer.py, pynumaflow/sinker/servicer/sync_servicer.py
Transition the multiproc servers to use UDS sockets instead of TCP
Fixes #161 
We can see equal CPU usage between the servers
=> chore: UDS based multiproc

pyproject.toml
=> chore: update release version 0.7.0

pynumaflow/sourcetransformer/multiproc_server.py
=> fix: udf type in multiproc source transformer

poetry.lock, pyproject.toml
=> chore: upgrade psutil

examples/map/even_odd/Makefile
=> chore: add missing dollar sign to variable

development.md, releases.md
=> chore: update development and releasing docs to reflect latest changes

.github/workflows/build-push.yaml
=> chore: fix broken path

pynumaflow/info/types.py, pyproject.toml
Prepare for upgrading to 0.8.0
=> chore: bump release version

examples/sideinput/simple_sideinput/udf/example.py
Ref: https://numaproj.slack.com/archives/C03GQ3AMHE1/p1729277713165089?thread_ts=1729144626.484519&cid=C03GQ3AMHE1
=> chore: update SideInput UDF example

pynumaflow/reducer/async_server.py, pynumaflow/reducestreamer/async_server.py, tests/reduce/test_async_reduce.py, tests/reducestreamer/test_async_reduce.py
partially fixes [#https://github.com/numaproj/numaflow-python/issues/168](https://github.com/numaproj/numaflow-python/issues/168)
=> chore: refactor reduce handler argument

.github/workflows/build-push.yaml
Need to pin the version in CI
refer: https://github.com/docker/setup-qemu-action/issues/198
=> chore: [TEMP] pin qemu version

pynumaflow/_constants.py, pynumaflow/batchmapper/servicer/async_servicer.py, pynumaflow/mapper/_servicer/_async_servicer.py, pynumaflow/mapper/_servicer/_sync_servicer.py, pynumaflow/mapstreamer/servicer/async_servicer.py, pynumaflow/reducer/servicer/async_servicer.py, pynumaflow/reducestreamer/servicer/async_servicer.py, pynumaflow/sideinput/servicer/servicer.py, pynumaflow/sinker/servicer/async_servicer.py, pynumaflow/sourcer/servicer/async_servicer.py, pynumaflow/sourcetransformer/servicer/_servicer.py, tests/sink/test_async_sink.py, tests/source/test_async_source_err.py
https://github.com/numaproj/numaflow/issues/2467
=> chore: ud-container env variable for formalising the errors

examples/map/async_multiproc_map/Dockerfile, examples/map/async_multiproc_map/Makefile, examples/map/async_multiproc_map/README.md, examples/map/async_multiproc_map/entry.sh, examples/map/async_multiproc_map/example.py, examples/map/async_multiproc_map/pipeline.yaml, examples/map/async_multiproc_map/pyproject.toml, pynumaflow/batchmapper/servicer/async_servicer.py, pynumaflow/info/types.py, pynumaflow/mapper/__init__.py, pynumaflow/mapper/_servicer/_async_servicer.py, pynumaflow/mapper/async_multiproc_server.py, pynumaflow/mapper/async_server.py, pynumaflow/mapstreamer/servicer/async_servicer.py, pynumaflow/reducer/servicer/async_servicer.py, pynumaflow/reducestreamer/servicer/async_servicer.py, pynumaflow/shared/server.py, pynumaflow/sinker/servicer/async_servicer.py, pynumaflow/sourcer/servicer/async_servicer.py, tests/source/test_async_source_err.py
=> [WIP]feat: async multiproc map

pyproject.toml
=> chore: release version v0.9.2

pyproject.toml
=> chore: prerelease for 0.10.0a0

poetry.lock, pyproject.toml, tests/map/test_multiproc_mapper.py
```
Vulnerabilities
===============
CVE               Severity    CVSS    CVE Introduced From Package    Package Version    Fixed In Version    Grace period ends on
---               --------    ----    ---------------------------    ---------------    ----------------    --------------------
CVE-2025-47273    high        7.7     setuptools                     75.8.0             78.1.1              NA
------------------------------------
------------------------------------
```
=> chore: fix cve with setuptools
