.codecov.yml, .coveragerc, .github/workflows/ci.yml, .github/workflows/coverage.yml, README.md, poetry.lock, pyproject.toml
=> chore: support Python 3.8, 3.9 and 3.10

.flake8, .github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, .github/workflows/lint.yml, Makefile, poetry.lock, pynumaflow/function/_dtypes.py, pynumaflow/sink/_dtypes.py, pynumaflow/tests/function/test_datatypes.py, pynumaflow/tests/function/test_server.py, pynumaflow/tests/sink/test_datatypes.py, pynumaflow/tests/sink/test_server.py, pyproject.toml
- Added linting
- Format code to pass linting
- Added flake8 dependency
- Added codeowners and other templates
=> chore: add linting workflow

examples/developer_guide/pipeline-numaflow.yaml, examples/function/counter/pyproject.toml, examples/function/flatmap/pyproject.toml, examples/function/forward_message/pyproject.toml, examples/sink/log/pyproject.toml
example images built, tested, and pushed.
```yaml
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
name: pynumasdk
spec:
vertices:
- name: in
source:
generator:
rpu: 10
duration: 1s
- name: flatmap
udf:
container:
image: quay.io/numaio/numaflow-python/map-flatmap:latest
- name: cat
udf:
container:
image: quay.io/numaio/numaflow-python/map-forward-message:latest
- name: counter
udf:
container:
image: quay.io/numaio/numaflow-python/reduce-counter:latest
groupBy:
window:
fixed:
length: 10s
keyed: true
- name: sink
scale:
min: 1
sink:
udsink:
container:
image: quay.io/numaio/numaflow-python/sink-log:latest
edges:
- from: in
to: flatmap
- from: flatmap
to: cat
- from: cat
to: counter
parallelism: 1
- from: counter
to: sink
```
=> chore: update example pynumaflow version

poetry.lock, pyproject.toml
Allow protobuf 3.20 and above to be used.
=> chore: allow protobuf 3.20 and above

pynumaflow/function/server.py
Adding named parameters to the UserDefinedFunctionServicer call to avoid mismatch.
=> chore: add named parameters to UDF call

examples/function/asyncio-reduce/README.md, pynumaflow/function/server.py
Fixes #63 
Save strong references of tasks/futures so that they are not lost mid execution due to GC.
=> fix: store strong references of task objects 

pynumaflow/function/server.py, pynumaflow/tests/function/test_async_server.py, pynumaflow/tests/function/test_async_server_err.py, pynumaflow/tests/function/test_server.py
closes #68 
Manual E2E Testing Notes:
After this change, if UDF throws an exception, the exception immediately get re-raised and Numaflow will keep retrying on failed messages until the exception gets resolved. In my test, since the exception never gets resolved, the retry keeps going on forever.
UDF numa log
```
ERROR 2023-03-30 15:03:46 {"level":"error","ts":1680203026.7438965,"logger":"numaflow.MapUDF-processor","caller":"forward/forward.go:561","msg":"UDF.Apply error","vertex":"err-test-throw-error","protocol":"uds-grpc-map-udf","error":"gRPC client.MapFn failed, failed to execute c.grpcClt.MapFn(): rpc error: code = Unknown desc = Exception calling application: Sorry, raising an exception","stacktrace":"github.com/numaproj/numaflow/pkg/forward.(*InterStepDataForward).applyUDF\n\t/User …
```
=> chore: re-raise UDFError instead of dropping messages

examples/function/asyncio-reduce/Makefile, examples/function/counter/Makefile, examples/function/even_odd/Makefile, examples/function/event_time_filter/Makefile, examples/function/flatmap/Makefile, examples/function/flatmap_stream/Makefile, examples/function/forward_message/Makefile, examples/function/multiproc_map/Makefile, examples/sink/async_log/Makefile, examples/sink/log/Makefile
If a developer uses a non `linux/amd64` laptop to build udf images, the built images won't work under the Github CI runner hence fail the E2E tests. This code change gives instructions on how to build multi-platform images such that developers can push images that support running E2E tests both locally and on Github CI.
=> chore: add instructions on building multi-platform images

pynumaflow/_constants.py, pynumaflow/sourcetransformer/__init__.py, pynumaflow/sourcetransformer/_dtypes.py, tests/sourcetransform/test_messages.py
Set the event time of messages to drop to epoch(0) - 1ms across all our SDKs.
=> chore: unify the event time of messages to drop

pynumaflow/sourcer/async_server.py
Fix typo in async_server.py. The function `add_sourceServicer_to_server` needs to read `add_SourceServicer_to_server`.
closes #117
=> fix: typo in async_server.py

pynumaflow/mapper/multiproc_server.py, pynumaflow/sourcetransformer/multiproc_server.py, tests/map/test_multiproc_mapper.py, tests/sourcetransform/test_multiproc.py
=> chore: update multiproc to use explicit ports for connection

pynumaflow/sideinput/server.py
Implements: [Issue 1457](https://github.com/numaproj/numaflow/issues/1457) for the Python sdk
=> chore: write server info for sideinput sdk

examples/map/flatmap/Makefile, examples/map/flatmap/pipeline.yaml, examples/map/flatmap/pyproject.toml, examples/mapstream/flatmap_stream/Makefile, examples/mapstream/flatmap_stream/pipeline.yaml, examples/mapstream/flatmap_stream/pyproject.toml, examples/sink/log/Makefile, examples/sink/log/pipeline-numaflow.yaml, examples/sink/log/pyproject.toml, examples/source/simple-source/Makefile, examples/source/simple-source/pipeline-numaflow.yaml, examples/source/simple-source/pyproject.toml, examples/sourcetransform/event_time_filter/Makefile, examples/sourcetransform/event_time_filter/pyproject.toml
Updating example images in order to use the newest sdk versions required to pass e2e tests in [#1456](https://github.com/numaproj/numaflow/issues/1456)
=> chore: update examples

pyproject.toml
Change release version to 0.7.0a0
Semantic versioning through `poetry version preminor`
=> chore: bump release version

.github/workflows/build-push.yaml, examples/sink/async_log/Dockerfile, examples/source/async_source/Dockerfile, examples/sourcetransform/event_time_filter/Makefile
=> chore: fix example paths for async_log and async_source

examples/sideinput/simple_sideinput/README.md
=> fix: update side-input readme

pynumaflow/info/types.py, pyproject.toml, tests/test_info_server.py
=> chore: update release version

.github/workflows/build-push.yaml, examples/batchmap/flatmap/Dockerfile, examples/map/even_odd/Dockerfile, examples/map/flatmap/Dockerfile, examples/map/forward_message/Dockerfile, examples/map/multiproc_map/Dockerfile, examples/mapstream/flatmap_stream/Dockerfile, examples/reduce/counter/Dockerfile, examples/reducestream/counter/Dockerfile, examples/reducestream/sum/Dockerfile, examples/sideinput/simple_sideinput/Dockerfile, examples/sideinput/simple_sideinput/udf/Dockerfile, examples/sink/async_log/Dockerfile, examples/sink/log/Dockerfile, examples/source/simple_source/Dockerfile, examples/sourcetransform/event_time_filter/Dockerfile
Have added this to unblock the builds currently, the poetry version is pinned in the example docker files which was causing the builds to fail. Hence we need to recreate with poetry lock.
This is temp fix, I will update the Dockerfiles to use an optimized version which I have for other use cases
=> chore: fix docker builds for examples

pynumaflow/_constants.py, pynumaflow/errors/__init__.py, pynumaflow/errors/_dtypes.py, pynumaflow/errors/errors.py, tests/errors/test_dtypes.py, tests/errors/test_persist_critical_error.py
Refer https://github.com/numaproj/numaflow/issues/2479
A new errors pkg with PersistCriticalError functionality for the user to persist a critical error and ultimately view it in the UI.
Go SDK PR https://github.com/numaproj/numaflow-go/pull/189
Java SDK PR https://github.com/numaproj/numaflow-java/pull/178
=> feat: utility function to persist critical error

examples/sourcetransform/async_event_time_filter/Dockerfile, examples/sourcetransform/async_event_time_filter/Makefile, examples/sourcetransform/async_event_time_filter/entry.sh, examples/sourcetransform/async_event_time_filter/example.py, examples/sourcetransform/async_event_time_filter/pyproject.toml, pynumaflow/sourcetransformer/__init__.py, pynumaflow/sourcetransformer/_dtypes.py, pynumaflow/sourcetransformer/async_server.py, pynumaflow/sourcetransformer/servicer/_async_servicer.py, tests/sourcetransform/test_async.py
fixes https://github.com/numaproj/numaflow-python/issues/70
=> feat: add async source transformer

pynumaflow/accumulator/_dtypes.py, pynumaflow/accumulator/servicer/task_manager.py, pynumaflow/batchmapper/_dtypes.py, pynumaflow/mapstreamer/_dtypes.py, pynumaflow/reducer/_dtypes.py, pynumaflow/reducer/servicer/task_manager.py, pynumaflow/reducestreamer/_dtypes.py, pynumaflow/reducestreamer/servicer/task_manager.py, pynumaflow/sourcetransformer/_dtypes.py, tests/accumulator/test_async_accumulator.py, tests/accumulator/test_async_accumulator_err.py, tests/accumulator/test_datatypes.py, tests/batchmap/test_datatypes.py, tests/reduce/test_datatypes.py, tests/reducestreamer/test_datatypes.py
Note that this is a breaking change; from now on, all the callers should call keys like `datum.keys`, not `datum.keys()`.
Close #233
=> chore: Datum keys as property

pynumaflow/mapstreamer/servicer/async_servicer.py, tests/mapstream/test_async_map_stream.py
This PR updates the Mapstreamer implementation to process multiple requests concurrently. Previously, requests were handled sequentially within a single async loop. With this change, each incoming request is dispatched to its own background task, allowing responses from different requests to be streamed back in parallel.
Testing code
```
class FlatMapStream(MapStreamer):
async def handler(self, keys: list[str], datum: Datum) -> AsyncIterable[Message]:
"""
A handler that splits the input datum value into multiple strings by `,` separator and
emits them as a stream.
"""
val = datum.value
_ = datum.event_time
_ = datum.watermark
strs = val.decode("utf-8").split(",")
current_time = time.time()
print(f"Starting task {current_time}")
yield Message(str.encode(f"Starting task {current_time}")) …
```
=> feat: parallelized mapstreamer

.github/workflows/run-tests.yml, poetry.lock, pyproject.toml, tests/map/test_multiproc_mapper.py, tests/map/test_sync_mapper.py, tests/sourcetransform/test_multiproc.py, tests/sourcetransform/test_sync_server.py
Python 3.13 support.
Imitates #166
=> chore: support Python 3.13

pynumaflow/sourcer/servicer/async_servicer.py, tests/source/test_async_source_err.py
Fix a syntax error. 
Also, the type of `request_iterator` in grpc streaming is an `AsyncIterator`, not `AsyncIterable` (https://grpc.io/docs/languages/python/basics/#request-streaming-rpc). We call `__anext__` in the body (if it was `AsyncIterable`, it should have been `request_iterator.__aiter__().__anext__()` or `anext(aiter(generator_response))` in Python > 3.10.
I'm also changing return type to be `AsyncIterator` (from `AsyncIterable`). Functionally, both are same and users shouldn't see any issues. The `AsyncIterator` is more restrictive, and is exhausted once iterated over. `AsyncIterable` indicates that the iterator can be created any number of times by calling `aiter(obj)`.
=> fix: Function call syntax error

Makefile, examples/source/simple_source/example.py, pynumaflow/proto/sourcer/source.proto, pynumaflow/proto/sourcer/source_pb2.py, pynumaflow/proto/sourcer/source_pb2.pyi, pynumaflow/proto/sourcer/source_pb2_grpc.py, pynumaflow/sourcer/__init__.py, pynumaflow/sourcer/_dtypes.py, pynumaflow/sourcer/async_server.py, pynumaflow/sourcer/servicer/async_servicer.py, tests/source/test_async_source.py, tests/source/test_async_source_err.py, tests/source/utils.py
Closes #248 
Implementation of https://github.com/numaproj/numaflow/issues/2923
Tested by running pipeline locally.
=> feat: Nack support for Sources
